"""add alert lifecycle fields

Revision ID: 633a4ce971c9
Revises: f0fdcf9d0801
Create Date: 2026-08-24 23:06:44.862996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '633a4ce971c9'
down_revision: Union[str, Sequence[str], None] = 'f0fdcf9d0801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('status', sa.String(), server_default='new', nullable=False))
    op.add_column('alerts', sa.Column('assigned_to', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('resolution_notes', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'updated_at')
    op.drop_column('alerts', 'resolution_notes')
    op.drop_column('alerts', 'assigned_to')
    op.drop_column('alerts', 'status')
    # ### end Alembic commands ###
